apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium/application.yaml
  - external-dns/application.yaml
  - cert-manager/application.yaml
  - envoy-gateway/application.yaml
  - reloader/application.yaml
  - cloudflared/application.yaml
  - velero/application.yaml
